// Copyright © 2026 Alexey Shulutkov <github@shulutkov.ru>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: discovery/v1/discovery.proto

// Package discovery.v1 is the stable wire contract for yellow-pages.
//
// APPEND-ONLY POLICY: this contract must remain backward compatible across a
// mixed-version mesh. Never renumber or retype an existing field and never
// reuse a field number; to drop a field, stop using it and add it to a
// `reserved` range. Errors are conveyed via gRPC status codes, never embedded
// in response bodies. All three transport adapters (native gRPC, Consul HTTP,
// Consul DNS) project this single contract. The buf breaking-gate (M8) enforces
// this from the first real change.

package discoveryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthState is the derived liveness of a service instance. maintenance is a
// separate flag (see ServiceEntry), not a health state.
type HealthState int32

const (
	HealthState_HEALTH_STATE_UNSPECIFIED HealthState = 0
	HealthState_HEALTH_STATE_PASSING     HealthState = 1
	HealthState_HEALTH_STATE_WARNING     HealthState = 2
	HealthState_HEALTH_STATE_CRITICAL    HealthState = 3
)

// Enum value maps for HealthState.
var (
	HealthState_name = map[int32]string{
		0: "HEALTH_STATE_UNSPECIFIED",
		1: "HEALTH_STATE_PASSING",
		2: "HEALTH_STATE_WARNING",
		3: "HEALTH_STATE_CRITICAL",
	}
	HealthState_value = map[string]int32{
		"HEALTH_STATE_UNSPECIFIED": 0,
		"HEALTH_STATE_PASSING":     1,
		"HEALTH_STATE_WARNING":     2,
		"HEALTH_STATE_CRITICAL":    3,
	}
)

func (x HealthState) Enum() *HealthState {
	p := new(HealthState)
	*p = x
	return p
}

func (x HealthState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthState) Descriptor() protoreflect.EnumDescriptor {
	return file_discovery_v1_discovery_proto_enumTypes[0].Descriptor()
}

func (HealthState) Type() protoreflect.EnumType {
	return &file_discovery_v1_discovery_proto_enumTypes[0]
}

func (x HealthState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthState.Descriptor instead.
func (HealthState) EnumDescriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{0}
}

// ChangeType classifies a Watch event.
type ChangeType int32

const (
	ChangeType_CHANGE_TYPE_UNSPECIFIED ChangeType = 0
	ChangeType_CHANGE_TYPE_PUT         ChangeType = 1
	ChangeType_CHANGE_TYPE_DELETE      ChangeType = 2
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "CHANGE_TYPE_UNSPECIFIED",
		1: "CHANGE_TYPE_PUT",
		2: "CHANGE_TYPE_DELETE",
	}
	ChangeType_value = map[string]int32{
		"CHANGE_TYPE_UNSPECIFIED": 0,
		"CHANGE_TYPE_PUT":         1,
		"CHANGE_TYPE_DELETE":      2,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_discovery_v1_discovery_proto_enumTypes[1].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_discovery_v1_discovery_proto_enumTypes[1]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{1}
}

// Weights influence load balancing. The default is {passing:1, warning:1};
// some balancers treat an absent weight as zero, so it is always populated on
// read surfaces.
type Weights struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passing       uint32                 `protobuf:"varint,1,opt,name=passing,proto3" json:"passing,omitempty"`
	Warning       uint32                 `protobuf:"varint,2,opt,name=warning,proto3" json:"warning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weights) Reset() {
	*x = Weights{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weights) ProtoMessage() {}

func (x *Weights) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weights.ProtoReflect.Descriptor instead.
func (*Weights) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *Weights) GetPassing() uint32 {
	if x != nil {
		return x.Passing
	}
	return 0
}

func (x *Weights) GetWarning() uint32 {
	if x != nil {
		return x.Warning
	}
	return 0
}

// Node identifies an agent and its node-scoped attributes. id is the stable
// agent identity carried on every RPC; datacenter is required by the Consul
// surfaces.
type Node struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address         string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Datacenter      string                 `protobuf:"bytes,4,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Meta            map[string]string      `protobuf:"bytes,5,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TaggedAddresses map[string]string      `protobuf:"bytes,6,rep,name=tagged_addresses,json=taggedAddresses,proto3" json:"tagged_addresses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Node) GetDatacenter() string {
	if x != nil {
		return x.Datacenter
	}
	return ""
}

func (x *Node) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Node) GetTaggedAddresses() map[string]string {
	if x != nil {
		return x.TaggedAddresses
	}
	return nil
}

// Service is one service instance definition. Identity within an agent is id
// (defaults to name); address/port are mutable data, not identity. tags are an
// ordered list of opaque raw strings — the source of truth (Consul parity).
type Service struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port    uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Tags    []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Meta    map[string]string      `protobuf:"bytes,6,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Weights *Weights               `protobuf:"bytes,7,opt,name=weights,proto3" json:"weights,omitempty"`
	// ttl_seconds is the per-service lease window; the server clamps it.
	TtlSeconds    uint32 `protobuf:"varint,8,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Service) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Service) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Service) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Service) GetWeights() *Weights {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *Service) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// Registration is the payload of Register: a node and its services plus the
// client-supplied data version. generation is identical on all seeds for one
// registration and is incremented only when endpoint/tags/meta change; Renew
// does not change it.
type Registration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Services      []*Service             `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	Generation    uint64                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{3}
}

func (x *Registration) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *Registration) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Registration) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

// ServiceEntry is a merged lookup/watch result: a service instance on a node
// with derived health. generation and last_seen_unix_nano drive the merge
// (max(generation) then max(last_seen)). last_seen is server-stamped.
type ServiceEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Node             *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Service          *Service               `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Health           HealthState            `protobuf:"varint,3,opt,name=health,proto3,enum=discovery.v1.HealthState" json:"health,omitempty"`
	Maintenance      bool                   `protobuf:"varint,4,opt,name=maintenance,proto3" json:"maintenance,omitempty"`
	Generation       uint64                 `protobuf:"varint,5,opt,name=generation,proto3" json:"generation,omitempty"`
	LastSeenUnixNano int64                  `protobuf:"varint,6,opt,name=last_seen_unix_nano,json=lastSeenUnixNano,proto3" json:"last_seen_unix_nano,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServiceEntry) Reset() {
	*x = ServiceEntry{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEntry) ProtoMessage() {}

func (x *ServiceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEntry.ProtoReflect.Descriptor instead.
func (*ServiceEntry) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceEntry) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ServiceEntry) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ServiceEntry) GetHealth() HealthState {
	if x != nil {
		return x.Health
	}
	return HealthState_HEALTH_STATE_UNSPECIFIED
}

func (x *ServiceEntry) GetMaintenance() bool {
	if x != nil {
		return x.Maintenance
	}
	return false
}

func (x *ServiceEntry) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ServiceEntry) GetLastSeenUnixNano() int64 {
	if x != nil {
		return x.LastSeenUnixNano
	}
	return 0
}

// Query selects service instances by exact name with optional filters. tags are
// matched against the raw tag strings (AND across multiple).
type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Datacenter    string                 `protobuf:"bytes,2,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	OnlyHealthy   bool                   `protobuf:"varint,4,opt,name=only_healthy,json=onlyHealthy,proto3" json:"only_healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{5}
}

func (x *Query) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Query) GetDatacenter() string {
	if x != nil {
		return x.Datacenter
	}
	return ""
}

func (x *Query) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Query) GetOnlyHealthy() bool {
	if x != nil {
		return x.OnlyHealthy
	}
	return false
}

// ChangeEvent is one entry-level change emitted by Watch.
type ChangeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ChangeType             `protobuf:"varint,1,opt,name=type,proto3,enum=discovery.v1.ChangeType" json:"type,omitempty"`
	Entry         *ServiceEntry          `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEvent) Reset() {
	*x = ChangeEvent{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEvent) ProtoMessage() {}

func (x *ChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEvent.ProtoReflect.Descriptor instead.
func (*ChangeEvent) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{6}
}

func (x *ChangeEvent) GetType() ChangeType {
	if x != nil {
		return x.Type
	}
	return ChangeType_CHANGE_TYPE_UNSPECIFIED
}

func (x *ChangeEvent) GetEntry() *ServiceEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registration  *Registration          `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterRequest) GetRegistration() *Registration {
	if x != nil {
		return x.Registration
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{8}
}

type RenewRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node_id renews ALL of this agent's services at once (idempotent node-scoped
	// convenience); per-service expiry remains authoritative.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// service_ids optionally narrows the renew to specific services.
	ServiceIds    []string `protobuf:"bytes,2,rep,name=service_ids,json=serviceIds,proto3" json:"service_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewRequest) Reset() {
	*x = RenewRequest{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRequest) ProtoMessage() {}

func (x *RenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRequest.ProtoReflect.Descriptor instead.
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{9}
}

func (x *RenewRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RenewRequest) GetServiceIds() []string {
	if x != nil {
		return x.ServiceIds
	}
	return nil
}

type RenewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewResponse) Reset() {
	*x = RenewResponse{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewResponse) ProtoMessage() {}

func (x *RenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewResponse.ProtoReflect.Descriptor instead.
func (*RenewResponse) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{10}
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{11}
}

func (x *DeregisterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{12}
}

type DeregisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServiceRequest) Reset() {
	*x = DeregisterServiceRequest{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServiceRequest) ProtoMessage() {}

func (x *DeregisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServiceRequest.ProtoReflect.Descriptor instead.
func (*DeregisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{13}
}

func (x *DeregisterServiceRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DeregisterServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type DeregisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServiceResponse) Reset() {
	*x = DeregisterServiceResponse{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServiceResponse) ProtoMessage() {}

func (x *DeregisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServiceResponse.ProtoReflect.Descriptor instead.
func (*DeregisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{14}
}

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *Query                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{15}
}

func (x *LookupRequest) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

type LookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ServiceEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{16}
}

func (x *LookupResponse) GetEntries() []*ServiceEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *LookupResponse) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Query *Query                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// index blocks until the registry index exceeds it (long poll). 0 returns
	// the current state immediately.
	Index         uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{17}
}

func (x *WatchRequest) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *WatchRequest) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type WatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Event *ChangeEvent           `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Index uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// snapshot_done marks the end of the initial state snapshot (a burst of put
	// events for the entries that already exist); subsequent responses are live
	// changes. Added in M8 (append-only).
	SnapshotDone  bool `protobuf:"varint,3,opt,name=snapshot_done,json=snapshotDone,proto3" json:"snapshot_done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{18}
}

func (x *WatchResponse) GetEvent() *ChangeEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *WatchResponse) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *WatchResponse) GetSnapshotDone() bool {
	if x != nil {
		return x.SnapshotDone
	}
	return false
}

type GetConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role is "agent" or "seed" (default "agent"). "seed" requires the cluster to
	// have allow_seed_join enabled, else PermissionDenied.
	Role          string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{19}
}

func (x *GetConfigRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GetConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// config is the rendered, sanitized YAML config (no TLS keys / ACL tokens).
	Config        []byte `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{20}
}

func (x *GetConfigResponse) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_discovery_v1_discovery_proto protoreflect.FileDescriptor

const file_discovery_v1_discovery_proto_rawDesc = "" +
	"\n" +
	"\x1cdiscovery/v1/discovery.proto\x12\fdiscovery.v1\"=\n" +
	"\aWeights\x12\x18\n" +
	"\apassing\x18\x01 \x01(\rR\apassing\x12\x18\n" +
	"\awarning\x18\x02 \x01(\rR\awarning\"\xe7\x02\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1e\n" +
	"\n" +
	"datacenter\x18\x04 \x01(\tR\n" +
	"datacenter\x120\n" +
	"\x04meta\x18\x05 \x03(\v2\x1c.discovery.v1.Node.MetaEntryR\x04meta\x12R\n" +
	"\x10tagged_addresses\x18\x06 \x03(\v2'.discovery.v1.Node.TaggedAddressesEntryR\x0ftaggedAddresses\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14TaggedAddressesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x02\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x123\n" +
	"\x04meta\x18\x06 \x03(\v2\x1f.discovery.v1.Service.MetaEntryR\x04meta\x12/\n" +
	"\aweights\x18\a \x01(\v2\x15.discovery.v1.WeightsR\aweights\x12\x1f\n" +
	"\vttl_seconds\x18\b \x01(\rR\n" +
	"ttlSeconds\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\fRegistration\x12&\n" +
	"\x04node\x18\x01 \x01(\v2\x12.discovery.v1.NodeR\x04node\x121\n" +
	"\bservices\x18\x02 \x03(\v2\x15.discovery.v1.ServiceR\bservices\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\"\x8b\x02\n" +
	"\fServiceEntry\x12&\n" +
	"\x04node\x18\x01 \x01(\v2\x12.discovery.v1.NodeR\x04node\x12/\n" +
	"\aservice\x18\x02 \x01(\v2\x15.discovery.v1.ServiceR\aservice\x121\n" +
	"\x06health\x18\x03 \x01(\x0e2\x19.discovery.v1.HealthStateR\x06health\x12 \n" +
	"\vmaintenance\x18\x04 \x01(\bR\vmaintenance\x12\x1e\n" +
	"\n" +
	"generation\x18\x05 \x01(\x04R\n" +
	"generation\x12-\n" +
	"\x13last_seen_unix_nano\x18\x06 \x01(\x03R\x10lastSeenUnixNano\"r\n" +
	"\x05Query\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"datacenter\x18\x02 \x01(\tR\n" +
	"datacenter\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12!\n" +
	"\fonly_healthy\x18\x04 \x01(\bR\vonlyHealthy\"m\n" +
	"\vChangeEvent\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.discovery.v1.ChangeTypeR\x04type\x120\n" +
	"\x05entry\x18\x02 \x01(\v2\x1a.discovery.v1.ServiceEntryR\x05entry\"Q\n" +
	"\x0fRegisterRequest\x12>\n" +
	"\fregistration\x18\x01 \x01(\v2\x1a.discovery.v1.RegistrationR\fregistration\"\x12\n" +
	"\x10RegisterResponse\"H\n" +
	"\fRenewRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vservice_ids\x18\x02 \x03(\tR\n" +
	"serviceIds\"\x0f\n" +
	"\rRenewResponse\",\n" +
	"\x11DeregisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\x14\n" +
	"\x12DeregisterResponse\"R\n" +
	"\x18DeregisterServiceRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\"\x1b\n" +
	"\x19DeregisterServiceResponse\":\n" +
	"\rLookupRequest\x12)\n" +
	"\x05query\x18\x01 \x01(\v2\x13.discovery.v1.QueryR\x05query\"\\\n" +
	"\x0eLookupResponse\x124\n" +
	"\aentries\x18\x01 \x03(\v2\x1a.discovery.v1.ServiceEntryR\aentries\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\"O\n" +
	"\fWatchRequest\x12)\n" +
	"\x05query\x18\x01 \x01(\v2\x13.discovery.v1.QueryR\x05query\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\"{\n" +
	"\rWatchResponse\x12/\n" +
	"\x05event\x18\x01 \x01(\v2\x19.discovery.v1.ChangeEventR\x05event\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12#\n" +
	"\rsnapshot_done\x18\x03 \x01(\bR\fsnapshotDone\"&\n" +
	"\x10GetConfigRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\"+\n" +
	"\x11GetConfigResponse\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config*z\n" +
	"\vHealthState\x12\x1c\n" +
	"\x18HEALTH_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14HEALTH_STATE_PASSING\x10\x01\x12\x18\n" +
	"\x14HEALTH_STATE_WARNING\x10\x02\x12\x19\n" +
	"\x15HEALTH_STATE_CRITICAL\x10\x03*V\n" +
	"\n" +
	"ChangeType\x12\x1b\n" +
	"\x17CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCHANGE_TYPE_PUT\x10\x01\x12\x16\n" +
	"\x12CHANGE_TYPE_DELETE\x10\x022\xdb\x03\n" +
	"\fAgentService\x12I\n" +
	"\bRegister\x12\x1d.discovery.v1.RegisterRequest\x1a\x1e.discovery.v1.RegisterResponse\x12@\n" +
	"\x05Renew\x12\x1a.discovery.v1.RenewRequest\x1a\x1b.discovery.v1.RenewResponse\x12O\n" +
	"\n" +
	"Deregister\x12\x1f.discovery.v1.DeregisterRequest\x1a .discovery.v1.DeregisterResponse\x12d\n" +
	"\x11DeregisterService\x12&.discovery.v1.DeregisterServiceRequest\x1a'.discovery.v1.DeregisterServiceResponse\x12C\n" +
	"\x06Lookup\x12\x1b.discovery.v1.LookupRequest\x1a\x1c.discovery.v1.LookupResponse\x12B\n" +
	"\x05Watch\x12\x1a.discovery.v1.WatchRequest\x1a\x1b.discovery.v1.WatchResponse0\x012`\n" +
	"\x10BootstrapService\x12L\n" +
	"\tGetConfig\x12\x1e.discovery.v1.GetConfigRequest\x1a\x1f.discovery.v1.GetConfigResponseB@Z>github.com/ks-tool/yellow-pages/proto/discovery/v1;discoveryv1b\x06proto3"

var (
	file_discovery_v1_discovery_proto_rawDescOnce sync.Once
	file_discovery_v1_discovery_proto_rawDescData []byte
)

func file_discovery_v1_discovery_proto_rawDescGZIP() []byte {
	file_discovery_v1_discovery_proto_rawDescOnce.Do(func() {
		file_discovery_v1_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discovery_v1_discovery_proto_rawDesc), len(file_discovery_v1_discovery_proto_rawDesc)))
	})
	return file_discovery_v1_discovery_proto_rawDescData
}

var file_discovery_v1_discovery_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_discovery_v1_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_discovery_v1_discovery_proto_goTypes = []any{
	(HealthState)(0),                  // 0: discovery.v1.HealthState
	(ChangeType)(0),                   // 1: discovery.v1.ChangeType
	(*Weights)(nil),                   // 2: discovery.v1.Weights
	(*Node)(nil),                      // 3: discovery.v1.Node
	(*Service)(nil),                   // 4: discovery.v1.Service
	(*Registration)(nil),              // 5: discovery.v1.Registration
	(*ServiceEntry)(nil),              // 6: discovery.v1.ServiceEntry
	(*Query)(nil),                     // 7: discovery.v1.Query
	(*ChangeEvent)(nil),               // 8: discovery.v1.ChangeEvent
	(*RegisterRequest)(nil),           // 9: discovery.v1.RegisterRequest
	(*RegisterResponse)(nil),          // 10: discovery.v1.RegisterResponse
	(*RenewRequest)(nil),              // 11: discovery.v1.RenewRequest
	(*RenewResponse)(nil),             // 12: discovery.v1.RenewResponse
	(*DeregisterRequest)(nil),         // 13: discovery.v1.DeregisterRequest
	(*DeregisterResponse)(nil),        // 14: discovery.v1.DeregisterResponse
	(*DeregisterServiceRequest)(nil),  // 15: discovery.v1.DeregisterServiceRequest
	(*DeregisterServiceResponse)(nil), // 16: discovery.v1.DeregisterServiceResponse
	(*LookupRequest)(nil),             // 17: discovery.v1.LookupRequest
	(*LookupResponse)(nil),            // 18: discovery.v1.LookupResponse
	(*WatchRequest)(nil),              // 19: discovery.v1.WatchRequest
	(*WatchResponse)(nil),             // 20: discovery.v1.WatchResponse
	(*GetConfigRequest)(nil),          // 21: discovery.v1.GetConfigRequest
	(*GetConfigResponse)(nil),         // 22: discovery.v1.GetConfigResponse
	nil,                               // 23: discovery.v1.Node.MetaEntry
	nil,                               // 24: discovery.v1.Node.TaggedAddressesEntry
	nil,                               // 25: discovery.v1.Service.MetaEntry
}
var file_discovery_v1_discovery_proto_depIdxs = []int32{
	23, // 0: discovery.v1.Node.meta:type_name -> discovery.v1.Node.MetaEntry
	24, // 1: discovery.v1.Node.tagged_addresses:type_name -> discovery.v1.Node.TaggedAddressesEntry
	25, // 2: discovery.v1.Service.meta:type_name -> discovery.v1.Service.MetaEntry
	2,  // 3: discovery.v1.Service.weights:type_name -> discovery.v1.Weights
	3,  // 4: discovery.v1.Registration.node:type_name -> discovery.v1.Node
	4,  // 5: discovery.v1.Registration.services:type_name -> discovery.v1.Service
	3,  // 6: discovery.v1.ServiceEntry.node:type_name -> discovery.v1.Node
	4,  // 7: discovery.v1.ServiceEntry.service:type_name -> discovery.v1.Service
	0,  // 8: discovery.v1.ServiceEntry.health:type_name -> discovery.v1.HealthState
	1,  // 9: discovery.v1.ChangeEvent.type:type_name -> discovery.v1.ChangeType
	6,  // 10: discovery.v1.ChangeEvent.entry:type_name -> discovery.v1.ServiceEntry
	5,  // 11: discovery.v1.RegisterRequest.registration:type_name -> discovery.v1.Registration
	7,  // 12: discovery.v1.LookupRequest.query:type_name -> discovery.v1.Query
	6,  // 13: discovery.v1.LookupResponse.entries:type_name -> discovery.v1.ServiceEntry
	7,  // 14: discovery.v1.WatchRequest.query:type_name -> discovery.v1.Query
	8,  // 15: discovery.v1.WatchResponse.event:type_name -> discovery.v1.ChangeEvent
	9,  // 16: discovery.v1.AgentService.Register:input_type -> discovery.v1.RegisterRequest
	11, // 17: discovery.v1.AgentService.Renew:input_type -> discovery.v1.RenewRequest
	13, // 18: discovery.v1.AgentService.Deregister:input_type -> discovery.v1.DeregisterRequest
	15, // 19: discovery.v1.AgentService.DeregisterService:input_type -> discovery.v1.DeregisterServiceRequest
	17, // 20: discovery.v1.AgentService.Lookup:input_type -> discovery.v1.LookupRequest
	19, // 21: discovery.v1.AgentService.Watch:input_type -> discovery.v1.WatchRequest
	21, // 22: discovery.v1.BootstrapService.GetConfig:input_type -> discovery.v1.GetConfigRequest
	10, // 23: discovery.v1.AgentService.Register:output_type -> discovery.v1.RegisterResponse
	12, // 24: discovery.v1.AgentService.Renew:output_type -> discovery.v1.RenewResponse
	14, // 25: discovery.v1.AgentService.Deregister:output_type -> discovery.v1.DeregisterResponse
	16, // 26: discovery.v1.AgentService.DeregisterService:output_type -> discovery.v1.DeregisterServiceResponse
	18, // 27: discovery.v1.AgentService.Lookup:output_type -> discovery.v1.LookupResponse
	20, // 28: discovery.v1.AgentService.Watch:output_type -> discovery.v1.WatchResponse
	22, // 29: discovery.v1.BootstrapService.GetConfig:output_type -> discovery.v1.GetConfigResponse
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_discovery_v1_discovery_proto_init() }
func file_discovery_v1_discovery_proto_init() {
	if File_discovery_v1_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discovery_v1_discovery_proto_rawDesc), len(file_discovery_v1_discovery_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_discovery_v1_discovery_proto_goTypes,
		DependencyIndexes: file_discovery_v1_discovery_proto_depIdxs,
		EnumInfos:         file_discovery_v1_discovery_proto_enumTypes,
		MessageInfos:      file_discovery_v1_discovery_proto_msgTypes,
	}.Build()
	File_discovery_v1_discovery_proto = out.File
	file_discovery_v1_discovery_proto_goTypes = nil
	file_discovery_v1_discovery_proto_depIdxs = nil
}
