/*
 Copyright © 2026 Alexey Shulutkov <github@shulutkov.ru>

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 	http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

// Package bootstrap lets a seed hand a generated, SANITIZED config to a joining
// agent/seed (feature-flagged, off by default) so cluster configs can be
// refreshed centrally without a config-management tool. It is a sensitive
// config-distribution channel: every request needs a token, joining as a SEED is
// separately gated, and the rendered config NEVER carries secret material (TLS
// keys, ACL tokens, the bootstrap token itself). See docs/bootstrap.md.
package bootstrap

import (
	"fmt"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/ks-tool/yellow-pages/internal/config"
)

// rendered is the curated, safe subset of a config served to a joining node.
// It exists as its own type (rather than reusing config.Config) so a secret
// field can never be added to the wire by accident.
type rendered struct {
	// node_name is deliberately absent: it must be node-unique and set locally,
	// so it is not even representable on the bootstrap wire.
	Role              string     `yaml:"role"`
	Datacenter        string     `yaml:"datacenter"`
	Cluster           rCluster   `yaml:"cluster"`
	TTL               string     `yaml:"ttl"`
	HeartbeatInterval string     `yaml:"heartbeat_interval"`
	ShutdownTimeout   string     `yaml:"shutdown_timeout"`
	MaxServices       int        `yaml:"max_services,omitempty"`
	Listeners         rListeners `yaml:"listeners"`
	DNS               *rDNS      `yaml:"dns,omitempty"`
	Agent             *rAgent    `yaml:"agent,omitempty"`
	TLS               *rTLS      `yaml:"tls,omitempty"`
	ACL               *rACL      `yaml:"acl,omitempty"`
}

type rCluster struct {
	Name  string   `yaml:"name"`
	Seeds []string `yaml:"seeds"`
}

type rListener struct {
	Enabled bool   `yaml:"enabled,omitempty"`
	Address string `yaml:"address"`
	Port    uint16 `yaml:"port"`
}

type rListeners struct {
	GRPC       rListener `yaml:"grpc"`
	ConsulHTTP rListener `yaml:"consul_http"`
	DNS        rListener `yaml:"dns"`
	Metrics    rListener `yaml:"metrics"`
}

type rDNS struct {
	Domain    string `yaml:"domain,omitempty"`
	AltDomain string `yaml:"alt_domain,omitempty"`
}

type rAgent struct {
	SeedTimeout   string `yaml:"seed_timeout,omitempty"`
	WriteQuorum   int    `yaml:"write_quorum,omitempty"`
	ReadyMinSeeds int    `yaml:"ready_min_seeds,omitempty"`
	DrainWindow   string `yaml:"drain_window,omitempty"`
	CacheMaxAge   string `yaml:"cache_max_age,omitempty"`
}

// rTLS carries only the on/off flags — NEVER cert/key/ca paths or contents. The
// node provisions its own credentials locally (out-of-band).
type rTLS struct {
	Enabled   bool `yaml:"enabled"`
	MutualTLS bool `yaml:"mutual_tls,omitempty"`
}

// rACL carries only the mode — NEVER the tokens file.
type rACL struct {
	Mode string `yaml:"mode"`
}

const renderHeader = "# Generated by `yp bootstrap` from a seed.\n" +
	"# SANITIZED: this carries no TLS keys / ACL tokens — provision node\n" +
	"# credentials locally (set tls.cert_file/key_file/ca_file, acl.tokens_file).\n\n"

// Render builds the sanitized YAML config for a joining node of the given role,
// advertising seeds as its seed list, derived from the serving seed's cfg.
func Render(cfg *config.Config, role config.Role, seeds []string) ([]byte, error) {
	loopback := "127.0.0.1"
	r := rendered{
		Role:              string(role),
		Datacenter:        cfg.Datacenter,
		Cluster:           rCluster{Name: cfg.Cluster.Name, Seeds: seeds},
		TTL:               cfg.TTL.String(),
		HeartbeatInterval: cfg.HeartbeatInterval.String(),
		ShutdownTimeout:   cfg.ShutdownTimeout.String(),
		Listeners: rListeners{
			GRPC:       rListener{Address: loopback, Port: cfg.Listeners.GRPC.Port},
			ConsulHTTP: rListener{Enabled: true, Address: loopback, Port: cfg.Listeners.ConsulHTTP.Port},
			DNS:        rListener{Enabled: true, Address: loopback, Port: cfg.Listeners.DNS.Port},
			Metrics:    rListener{Address: loopback, Port: cfg.Listeners.Metrics.Port},
		},
	}
	if role == config.RoleSeed {
		r.MaxServices = cfg.MaxServices
	}
	if cfg.DNS.Domain != "" || cfg.DNS.AltDomain != "" {
		r.DNS = &rDNS{Domain: cfg.DNS.Domain, AltDomain: cfg.DNS.AltDomain}
	}
	if role == config.RoleAgent {
		r.Agent = &rAgent{
			SeedTimeout:   durStr(cfg.Agent.SeedTimeout),
			WriteQuorum:   cfg.Agent.WriteQuorum,
			ReadyMinSeeds: cfg.Agent.ReadyMinSeeds,
			DrainWindow:   durStr(cfg.Agent.DrainWindow),
			CacheMaxAge:   durStr(cfg.Agent.CacheMaxAge),
		}
	}
	if cfg.TLS.Enabled {
		r.TLS = &rTLS{Enabled: true, MutualTLS: cfg.TLS.MutualTLS}
	}
	if cfg.ACL.Mode != "" && cfg.ACL.Mode != "disabled" {
		r.ACL = &rACL{Mode: cfg.ACL.Mode}
	}

	body, err := yaml.Marshal(r)
	if err != nil {
		return nil, fmt.Errorf("bootstrap: render config: %w", err)
	}
	return append([]byte(renderHeader), body...), nil
}

func durStr(d time.Duration) string {
	if d == 0 {
		return ""
	}
	return d.String()
}
